#
#
#

#玩家右键勋章后提示的信息
message: "&6勋章已被收集！"

#自定义奖励
#按序号来，0 - 53，最多到53
reward:
  0:
    #需要收集多少勋章
    number: 5
    #显示的什么物品材质
    material: WATCH
    #介绍lore
    #需要收集勋章的数量 %number%
    lore:
      - "&6好吧，你要领取需要收集%number%个勋章"
      - "&6给你们送点福利！"
    #执行命令
    #玩家变量%player%
    commands:
      - "say 执行奖励命令"